################################################################################
version: '3.4'
################################################################################

networks:
  fakenet:
    driver: bridge

################################################################################

services:

  rmq:
    hostname: "rmq"
    image: "rabbitmq:3.7.28"
    #image: "rabbitmq:alpine"
    networks:
      - "fakenet"
    ports:
      - "5672:5672"
    healthcheck:
      test: "rabbitmq-diagnostics -q ping"
      interval: 30s
      timeout: 30s
      retries: 3

  pdb:
    # Checkout https://hub.docker.com/_/postgres for more info
    hostname: "pdb"
    image: "postgres:latest"
    #image: "postgres:alpine"
    networks:
      - "fakenet"
    ports:
      - 5432:5432
    user: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: main_aiidadb
    volumes:
      #- "./deploy/pdb:/docker-entrypoint-initdb.d" # For init scripts, only run if data dir is empty
      - "./data/dbase:/var/lib/postgresql/data" # For data persistence
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  workenv:
    hostname: "aiida"
    image: "aiida_workenv:v0.3"
    ports: # local:container
      - 8888 #:8888
      - 8890 #:8890
      - 5000 #:5000
    volumes:
      - "./data/codes:/root/codes"
      - "./data/aiida:/root/.aiida"
      - "./data/ssh:/root/.ssh"
      - "./data/config/init_extras.sh:/etc/my_init.d/30_init_extras.sh"
      - "./data/config/profile_extras.sh:/etc/profile.d/profile_extras.sh"
      - "./data/config/bashrc_extras.sh:/root/.bashrc_extras"
    depends_on:
      pdb:
        condition: service_healthy
      rmq:
        condition: service_healthy
    networks:
      - "fakenet"
    environment:
      LC_ALL: "en_US.UTF-8"
      LANG: "en_US.UTF-8"
      RMQ_HOST: rmq
      RMQ_PORT: "5672"
      PSQL_HOST: pdb
      PSQL_PORT: "5432"
      PGHOST: pdb
      PGPORT: "5432"
      PGUSER: "postgres"
      PGPASSWORD: "postgres"
    healthcheck:
      test: bash -c "[ -f /opt/INIT_COMPLETED ]"
      start_period: 30s
      interval: 30s
      timeout: 5s
      retries: 6

################################################################################
